#!/bin/sh
#Example of commands needed to run MegaDetector on its own for a folder of images.
#This assumes the virtual environment is activated, else uncomment the command to activate and deactivate.
# A JSON file containing detections of animals will be generated by MD, this will be used to crop the images


#source venv_zebra/bin/activate

cd ..
source  venv_zebra/bin/activate
export PYTHONPATH="$PYTHONPATH:$(realpath AnimalDetection/CameraTraps):$(realpath AnimalDetection/ai4utils)"
python AnimalDetection/CameraTraps/detection/run_detector_batch.py models/md_v4.1.0.pb /user/work/gh18931/diss/datasets/md_dataset/  md_detection_output.json

python scripts/animal_crop.py --input_filepath=md_detection_output.json --output_filepath=MD_output

#deactivate
